export type PossibleSublassNames =
  | "Life Domain"
  | "Light Domain"
  | "Trickery Domain"
  | "Knowledge Domain"
  | "Nature Domain"
  | "Tempest Domain"
  | "War Domain"
  | "Battle Master"
  | "Eldritch Knight"
  | "Champion"
  | "Beast Master"
  | "Hunter"
  | "Gloom Stalker"
  | "Thief"
  | "Arcane Trickster"
  | "Assassin"
  | "The Fiend"
  | "The Great Old One"
  | "Archfey"
  | "Abjuration School"
  | "Evocation School"
  | "Conjuration School"
  | "Divination School"
  | "Enchantment School"
  | "Illusion School"
  | "Necromancy School"
  | "Transmutation School"
  | "Circle of the Moon"
  | "Circle of the Land"
  | "Circle of Spores"
  | "Draconic Bloodline"
  | "Wild Magic"
  | "Storm Sorcery"
  | "Berserker"
  | "Wildheart"
  | "College of Lore"
  | "College of Valour"
  | "College of Swords"
  | "Oath of the Ancients"
  | "Oath of Devotion"
  | "Oathbreaker"
  | "Oath of Vengeance"
  | "Way of the Open Hand"
  | "Way of Shadow"
  | "Way of the Four Elements"
